on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  development:
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Call build and deploy
        uses: build-push-aws-ecr.yml
        with:
          deploy_env: development
          ecs_env_cluster: pipeline

  production:
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Call build and deploy
        uses: build-push-aws-ecr.yml
        with:
          deploy_env: production
          ecs_env_cluster: pipeline

