on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  development:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-push-aws_ecr.yml
    with:
      deploy_env: development
      ecs_env_cluster: pipeline

  production:
    uses: ./.github/workflows/build-push-aws_ecr.yml
    with:
      deploy_env: production
      ecs_env_cluster: pipeline

