on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  development:
    environment: development
    uses: build-push-aws-ecr.yml
    with:
      deploy_env: development
      ecs_env_cluster: pipeline

  production:
    environment: production
    uses: build-push-aws-ecr.yml
    with:
      deploy_env: production
      ecs_env_cluster: pipeline
