name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "dock44den" --password-stdin
        docker image build -t atuprojectstudioghiblis:latest .
        docker push atuprojectstudioghiblis:latest
      
      
      
